/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:charSelectionLogo;
new PlayerText:charSelectionTextDraw[MAX_PLAYERS];
new PlayerText:textdraw_2[MAX_PLAYERS];
new PlayerText:charSelectionTextDraw[MAX_PLAYERS];
new PlayerText:charSelectionTextDraw[MAX_PLAYERS];

//TEXTDRAWS
charSelectionLogo = TextDrawCreate(220.000000, 33.000000, "mdl-2001:logo");
TextDrawFont(charSelectionLogo, 4);
TextDrawLetterSize(charSelectionLogo, 0.600000, 2.000000);
TextDrawTextSize(charSelectionLogo, 204.500000, 76.000000);
TextDrawSetOutline(charSelectionLogo, 0);
TextDrawSetShadow(charSelectionLogo, 0);
TextDrawAlignment(charSelectionLogo, 1);
TextDrawColor(charSelectionLogo, -1);
TextDrawBackgroundColor(charSelectionLogo, 255);
TextDrawBoxColor(charSelectionLogo, 50);
TextDrawUseBox(charSelectionLogo, 1);
TextDrawSetProportional(charSelectionLogo, 1);
TextDrawSetSelectable(charSelectionLogo, 0);

charSelectionTextDraw[playerid] = CreatePlayerTextDraw(playerid, 318.000000, 121.000000, "_");
PlayerTextDrawFont(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawLetterSize(playerid, charSelectionTextDraw[playerid], 0.595833, 16.450000);
PlayerTextDrawTextSize(playerid, charSelectionTextDraw[playerid], 255.500000, 148.500000);
PlayerTextDrawSetOutline(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawSetShadow(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawAlignment(playerid, charSelectionTextDraw[playerid], 2);
PlayerTextDrawColor(playerid, charSelectionTextDraw[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, charSelectionTextDraw[playerid], 255);
PlayerTextDrawBoxColor(playerid, charSelectionTextDraw[playerid], 70);
PlayerTextDrawUseBox(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawSetProportional(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawSetSelectable(playerid, charSelectionTextDraw[playerid], 0);

textdraw_2[playerid] = CreatePlayerTextDraw(playerid, 318.000000, 285.000000, "_");
PlayerTextDrawFont(playerid, textdraw_2[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_2[playerid], 0.595833, 16.450000);
PlayerTextDrawTextSize(playerid, textdraw_2[playerid], 255.500000, 148.500000);
PlayerTextDrawSetOutline(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_2[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_2[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_2[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_2[playerid], 70);
PlayerTextDrawUseBox(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_2[playerid], 0);

charSelectionTextDraw[playerid] = CreatePlayerTextDraw(playerid, 245.000000, 121.000000, "Sarah Eisenhower~n~Level 6");
PlayerTextDrawFont(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawLetterSize(playerid, charSelectionTextDraw[playerid], 0.183329, 0.849995);
PlayerTextDrawTextSize(playerid, charSelectionTextDraw[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawSetShadow(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawAlignment(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawColor(playerid, charSelectionTextDraw[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, charSelectionTextDraw[playerid], 255);
PlayerTextDrawBoxColor(playerid, charSelectionTextDraw[playerid], 50);
PlayerTextDrawUseBox(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawSetProportional(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawSetSelectable(playerid, charSelectionTextDraw[playerid], 0);

charSelectionTextDraw[playerid] = CreatePlayerTextDraw(playerid, 235.000000, 134.000000, "Preview_Model");
PlayerTextDrawFont(playerid, charSelectionTextDraw[playerid], 5);
PlayerTextDrawLetterSize(playerid, charSelectionTextDraw[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, charSelectionTextDraw[playerid], 166.500000, 140.500000);
PlayerTextDrawSetOutline(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawSetShadow(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawAlignment(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawColor(playerid, charSelectionTextDraw[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawBoxColor(playerid, charSelectionTextDraw[playerid], 255);
PlayerTextDrawUseBox(playerid, charSelectionTextDraw[playerid], 0);
PlayerTextDrawSetProportional(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawSetSelectable(playerid, charSelectionTextDraw[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, charSelectionTextDraw[playerid], 23);
PlayerTextDrawSetPreviewRot(playerid, charSelectionTextDraw[playerid], -8.000000, 0.000000, -1.000000, 0.979999);
PlayerTextDrawSetPreviewVehCol(playerid, charSelectionTextDraw[playerid], 1, 1);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.

SelectTextDraw(playerid, 0xFF0000FF); //Shows cursor for player to select textdraw