/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:textdraw_0;

//TEXTDRAWS
textdraw_0 = TextDrawCreate(512.000000, 359.000000, "mdl-2001:logo");
TextDrawFont(textdraw_0, 4);
TextDrawLetterSize(textdraw_0, 0.600000, 2.000000);
TextDrawTextSize(textdraw_0, 139.000000, 91.500000);
TextDrawSetOutline(textdraw_0, 1);
TextDrawSetShadow(textdraw_0, 0);
TextDrawAlignment(textdraw_0, 1);
TextDrawColor(textdraw_0, -1);
TextDrawBackgroundColor(textdraw_0, 255);
TextDrawBoxColor(textdraw_0, 50);
TextDrawUseBox(textdraw_0, 1);
TextDrawSetProportional(textdraw_0, 1);
TextDrawSetSelectable(textdraw_0, 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.
