/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:bg_vhp;
new Text:bg_bar_vhp;
new PlayerText:bar_vhp[MAX_PLAYERS];
new Text:bg_lock;
new PlayerText:kmh[MAX_PLAYERS];
new Text:textdraw_5;
new PlayerText:textdraw_4[MAX_PLAYERS];
new Text:textdraw_8;
new Text:bg_kmh;
new Text:ui_bgBarGas;
new Text:bg_bar_gas;
new Text:textdraw_13;
new Text:textdraw_14;
new Text:bg_stats;
new Text:textdraw_16;
new PlayerText:bar_gas[MAX_PLAYERS];
new Text:textdraw_18;
new PlayerText:miles[MAX_PLAYERS];
new PlayerText:HUDZone[MAX_PLAYERS];

//TEXTDRAWS
bg_vhp = TextDrawCreate(542.000000, 410.000000, "_");
TextDrawFont(bg_vhp, 1);
TextDrawLetterSize(bg_vhp, 0.600000, 1.550004);
TextDrawTextSize(bg_vhp, 631.500000, 60.000000);
TextDrawSetOutline(bg_vhp, 1);
TextDrawSetShadow(bg_vhp, 0);
TextDrawAlignment(bg_vhp, 1);
TextDrawColor(bg_vhp, 255);
TextDrawBackgroundColor(bg_vhp, 255);
TextDrawBoxColor(bg_vhp, 421075455);
TextDrawUseBox(bg_vhp, 1);
TextDrawSetProportional(bg_vhp, 1);
TextDrawSetSelectable(bg_vhp, 0);

bg_bar_vhp = TextDrawCreate(558.000000, 417.000000, "_");
TextDrawFont(bg_bar_vhp, 1);
TextDrawLetterSize(bg_bar_vhp, 0.508328, -0.049995);
TextDrawTextSize(bg_bar_vhp, 615.000000, 26.000000);
TextDrawSetOutline(bg_bar_vhp, 1);
TextDrawSetShadow(bg_bar_vhp, 0);
TextDrawAlignment(bg_bar_vhp, 1);
TextDrawColor(bg_bar_vhp, -1138283009);
TextDrawBackgroundColor(bg_bar_vhp, 255);
TextDrawBoxColor(bg_bar_vhp, 252645375);
TextDrawUseBox(bg_bar_vhp, 1);
TextDrawSetProportional(bg_bar_vhp, 1);
TextDrawSetSelectable(bg_bar_vhp, 0);

bar_vhp[playerid] = CreatePlayerTextDraw(playerid, 558.000000, 417.000000, "_");
PlayerTextDrawFont(playerid, bar_vhp[playerid], 1);
PlayerTextDrawLetterSize(playerid, bar_vhp[playerid], 0.508328, -0.049995);
PlayerTextDrawTextSize(playerid, bar_vhp[playerid], 593.500000, 26.000000);
PlayerTextDrawSetOutline(playerid, bar_vhp[playerid], 1);
PlayerTextDrawSetShadow(playerid, bar_vhp[playerid], 0);
PlayerTextDrawAlignment(playerid, bar_vhp[playerid], 1);
PlayerTextDrawColor(playerid, bar_vhp[playerid], -1138283009);
PlayerTextDrawBackgroundColor(playerid, bar_vhp[playerid], 255);
PlayerTextDrawBoxColor(playerid, bar_vhp[playerid], -1138283009);
PlayerTextDrawUseBox(playerid, bar_vhp[playerid], 1);
PlayerTextDrawSetProportional(playerid, bar_vhp[playerid], 1);
PlayerTextDrawSetSelectable(playerid, bar_vhp[playerid], 0);

bg_lock = TextDrawCreate(525.000000, 410.000000, "_");
TextDrawFont(bg_lock, 1);
TextDrawLetterSize(bg_lock, 0.600000, 1.550004);
TextDrawTextSize(bg_lock, 537.000000, 60.000000);
TextDrawSetOutline(bg_lock, 1);
TextDrawSetShadow(bg_lock, 0);
TextDrawAlignment(bg_lock, 1);
TextDrawColor(bg_lock, 255);
TextDrawBackgroundColor(bg_lock, 255);
TextDrawBoxColor(bg_lock, 421075455);
TextDrawUseBox(bg_lock, 1);
TextDrawSetProportional(bg_lock, 1);
TextDrawSetSelectable(bg_lock, 0);

kmh[playerid] = CreatePlayerTextDraw(playerid, 542.000000, 373.000000, "0");
PlayerTextDrawFont(playerid, kmh[playerid], 2);
PlayerTextDrawLetterSize(playerid, kmh[playerid], 0.345831, 1.899996);
PlayerTextDrawTextSize(playerid, kmh[playerid], 618.000000, 15.000000);
PlayerTextDrawSetOutline(playerid, kmh[playerid], 0);
PlayerTextDrawSetShadow(playerid, kmh[playerid], 1);
PlayerTextDrawAlignment(playerid, kmh[playerid], 2);
PlayerTextDrawColor(playerid, kmh[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, kmh[playerid], 255);
PlayerTextDrawBoxColor(playerid, kmh[playerid], 50);
PlayerTextDrawUseBox(playerid, kmh[playerid], 0);
PlayerTextDrawSetProportional(playerid, kmh[playerid], 1);
PlayerTextDrawSetSelectable(playerid, kmh[playerid], 0);

textdraw_5 = TextDrawCreate(532.000000, 390.000000, "KM/H");
TextDrawFont(textdraw_5, 2);
TextDrawLetterSize(textdraw_5, 0.204162, 1.250000);
TextDrawTextSize(textdraw_5, 618.000000, 15.000000);
TextDrawSetOutline(textdraw_5, 0);
TextDrawSetShadow(textdraw_5, 1);
TextDrawAlignment(textdraw_5, 1);
TextDrawColor(textdraw_5, -1);
TextDrawBackgroundColor(textdraw_5, 255);
TextDrawBoxColor(textdraw_5, 50);
TextDrawUseBox(textdraw_5, 0);
TextDrawSetProportional(textdraw_5, 1);
TextDrawSetSelectable(textdraw_5, 0);

textdraw_4[playerid] = CreatePlayerTextDraw(playerid, 526.000000, 411.000000, "mdl-2001:Locks-Unlocked");
PlayerTextDrawFont(playerid, textdraw_4[playerid], 4);
PlayerTextDrawLetterSize(playerid, textdraw_4[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, textdraw_4[playerid], 10.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_4[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_4[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_4[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_4[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_4[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_4[playerid], 0);

textdraw_8 = TextDrawCreate(620.000000, 412.000000, "mdl-2001:Fire-Off");
TextDrawFont(textdraw_8, 4);
TextDrawLetterSize(textdraw_8, 0.600000, 2.000000);
TextDrawTextSize(textdraw_8, 10.000000, 10.000000);
TextDrawSetOutline(textdraw_8, 1);
TextDrawSetShadow(textdraw_8, 0);
TextDrawAlignment(textdraw_8, 1);
TextDrawColor(textdraw_8, -1);
TextDrawBackgroundColor(textdraw_8, 255);
TextDrawBoxColor(textdraw_8, 50);
TextDrawUseBox(textdraw_8, 1);
TextDrawSetProportional(textdraw_8, 1);
TextDrawSetSelectable(textdraw_8, 0);

bg_kmh = TextDrawCreate(525.000000, 374.000000, "_");
TextDrawFont(bg_kmh, 1);
TextDrawLetterSize(bg_kmh, 0.600000, 3.299998);
TextDrawTextSize(bg_kmh, 559.000000, 60.000000);
TextDrawSetOutline(bg_kmh, 1);
TextDrawSetShadow(bg_kmh, 0);
TextDrawAlignment(bg_kmh, 1);
TextDrawColor(bg_kmh, 255);
TextDrawBackgroundColor(bg_kmh, 255);
TextDrawBoxColor(bg_kmh, 421075455);
TextDrawUseBox(bg_kmh, 1);
TextDrawSetProportional(bg_kmh, 1);
TextDrawSetSelectable(bg_kmh, 0);

ui_bgBarGas = TextDrawCreate(564.000000, 390.000000, "_");
TextDrawFont(ui_bgBarGas, 1);
TextDrawLetterSize(ui_bgBarGas, 0.600000, 1.550004);
TextDrawTextSize(ui_bgBarGas, 631.000000, 60.000000);
TextDrawSetOutline(ui_bgBarGas, 1);
TextDrawSetShadow(ui_bgBarGas, 0);
TextDrawAlignment(ui_bgBarGas, 1);
TextDrawColor(ui_bgBarGas, 255);
TextDrawBackgroundColor(ui_bgBarGas, 255);
TextDrawBoxColor(ui_bgBarGas, 421075455);
TextDrawUseBox(ui_bgBarGas, 1);
TextDrawSetProportional(ui_bgBarGas, 1);
TextDrawSetSelectable(ui_bgBarGas, 0);

bg_bar_gas = TextDrawCreate(564.000000, 390.000000, "_");
TextDrawFont(bg_bar_gas, 1);
TextDrawLetterSize(bg_bar_gas, 0.508328, -0.049995);
TextDrawTextSize(bg_bar_gas, 631.000000, 26.000000);
TextDrawSetOutline(bg_bar_gas, 1);
TextDrawSetShadow(bg_bar_gas, 0);
TextDrawAlignment(bg_bar_gas, 1);
TextDrawColor(bg_bar_gas, -1138283009);
TextDrawBackgroundColor(bg_bar_gas, 255);
TextDrawBoxColor(bg_bar_gas, 252645375);
TextDrawUseBox(bg_bar_gas, 1);
TextDrawSetProportional(bg_bar_gas, 1);
TextDrawSetSelectable(bg_bar_gas, 0);

textdraw_13 = TextDrawCreate(580.000000, 394.000000, "mdl-2001:Fuel");
TextDrawFont(textdraw_13, 4);
TextDrawLetterSize(textdraw_13, 0.600000, 2.000000);
TextDrawTextSize(textdraw_13, 10.000000, 10.000000);
TextDrawSetOutline(textdraw_13, 1);
TextDrawSetShadow(textdraw_13, 0);
TextDrawAlignment(textdraw_13, 1);
TextDrawColor(textdraw_13, -1);
TextDrawBackgroundColor(textdraw_13, 255);
TextDrawBoxColor(textdraw_13, 50);
TextDrawUseBox(textdraw_13, 1);
TextDrawSetProportional(textdraw_13, 1);
TextDrawSetSelectable(textdraw_13, 0);

textdraw_14 = TextDrawCreate(592.000000, 393.000000, "Fuel");
TextDrawFont(textdraw_14, 2);
TextDrawLetterSize(textdraw_14, 0.204162, 1.250000);
TextDrawTextSize(textdraw_14, 618.000000, 15.000000);
TextDrawSetOutline(textdraw_14, 0);
TextDrawSetShadow(textdraw_14, 0);
TextDrawAlignment(textdraw_14, 1);
TextDrawColor(textdraw_14, -1);
TextDrawBackgroundColor(textdraw_14, 255);
TextDrawBoxColor(textdraw_14, 50);
TextDrawUseBox(textdraw_14, 0);
TextDrawSetProportional(textdraw_14, 1);
TextDrawSetSelectable(textdraw_14, 0);

bg_stats = TextDrawCreate(564.000000, 374.000000, "_");
TextDrawFont(bg_stats, 1);
TextDrawLetterSize(bg_stats, 0.600000, 1.150004);
TextDrawTextSize(bg_stats, 631.500000, 60.000000);
TextDrawSetOutline(bg_stats, 1);
TextDrawSetShadow(bg_stats, 0);
TextDrawAlignment(bg_stats, 1);
TextDrawColor(bg_stats, 255);
TextDrawBackgroundColor(bg_stats, 255);
TextDrawBoxColor(bg_stats, 421075455);
TextDrawUseBox(bg_stats, 1);
TextDrawSetProportional(bg_stats, 1);
TextDrawSetSelectable(bg_stats, 0);

textdraw_16 = TextDrawCreate(565.000000, 375.000000, "mdl-2001:Lights");
TextDrawFont(textdraw_16, 4);
TextDrawLetterSize(textdraw_16, 0.600000, 2.000000);
TextDrawTextSize(textdraw_16, 10.000000, 10.000000);
TextDrawSetOutline(textdraw_16, 1);
TextDrawSetShadow(textdraw_16, 0);
TextDrawAlignment(textdraw_16, 1);
TextDrawColor(textdraw_16, -1);
TextDrawBackgroundColor(textdraw_16, 255);
TextDrawBoxColor(textdraw_16, 50);
TextDrawUseBox(textdraw_16, 1);
TextDrawSetProportional(textdraw_16, 1);
TextDrawSetSelectable(textdraw_16, 0);

bar_gas[playerid] = CreatePlayerTextDraw(playerid, 564.000000, 390.000000, "_");
PlayerTextDrawFont(playerid, bar_gas[playerid], 1);
PlayerTextDrawLetterSize(playerid, bar_gas[playerid], 0.508328, -0.049995);
PlayerTextDrawTextSize(playerid, bar_gas[playerid], 631.000000, 26.000000);
PlayerTextDrawSetOutline(playerid, bar_gas[playerid], 1);
PlayerTextDrawSetShadow(playerid, bar_gas[playerid], 0);
PlayerTextDrawAlignment(playerid, bar_gas[playerid], 1);
PlayerTextDrawColor(playerid, bar_gas[playerid], -1138283009);
PlayerTextDrawBackgroundColor(playerid, bar_gas[playerid], 255);
PlayerTextDrawBoxColor(playerid, bar_gas[playerid], 1168161535);
PlayerTextDrawUseBox(playerid, bar_gas[playerid], 1);
PlayerTextDrawSetProportional(playerid, bar_gas[playerid], 1);
PlayerTextDrawSetSelectable(playerid, bar_gas[playerid], 0);

textdraw_18 = TextDrawCreate(543.000000, 412.000000, "mdl-2001:Fire-On");
TextDrawFont(textdraw_18, 4);
TextDrawLetterSize(textdraw_18, 0.600000, 2.000000);
TextDrawTextSize(textdraw_18, 10.000000, 10.000000);
TextDrawSetOutline(textdraw_18, 1);
TextDrawSetShadow(textdraw_18, 0);
TextDrawAlignment(textdraw_18, 1);
TextDrawColor(textdraw_18, -1);
TextDrawBackgroundColor(textdraw_18, 255);
TextDrawBoxColor(textdraw_18, 50);
TextDrawUseBox(textdraw_18, 1);
TextDrawSetProportional(textdraw_18, 1);
TextDrawSetSelectable(textdraw_18, 0);

miles[playerid] = CreatePlayerTextDraw(playerid, 630.000000, 373.000000, "619 MI");
PlayerTextDrawFont(playerid, miles[playerid], 2);
PlayerTextDrawLetterSize(playerid, miles[playerid], 0.204162, 1.250000);
PlayerTextDrawTextSize(playerid, miles[playerid], 618.000000, 15.000000);
PlayerTextDrawSetOutline(playerid, miles[playerid], 0);
PlayerTextDrawSetShadow(playerid, miles[playerid], 0);
PlayerTextDrawAlignment(playerid, miles[playerid], 3);
PlayerTextDrawColor(playerid, miles[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, miles[playerid], 255);
PlayerTextDrawBoxColor(playerid, miles[playerid], 50);
PlayerTextDrawUseBox(playerid, miles[playerid], 0);
PlayerTextDrawSetProportional(playerid, miles[playerid], 1);
PlayerTextDrawSetSelectable(playerid, miles[playerid], 0);

HUDZone[playerid] = CreatePlayerTextDraw(playerid, 635.000000, 428.000000, "Highway 48");
PlayerTextDrawFont(playerid, HUDZone[playerid], 2);
PlayerTextDrawLetterSize(playerid, HUDZone[playerid], 0.258329, 1.499994);
PlayerTextDrawTextSize(playerid, HUDZone[playerid], 431.500000, 0.500000);
PlayerTextDrawSetOutline(playerid, HUDZone[playerid], 1);
PlayerTextDrawSetShadow(playerid, HUDZone[playerid], 0);
PlayerTextDrawAlignment(playerid, HUDZone[playerid], 3);
PlayerTextDrawColor(playerid, HUDZone[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HUDZone[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUDZone[playerid], 50);
PlayerTextDrawUseBox(playerid, HUDZone[playerid], 0);
PlayerTextDrawSetProportional(playerid, HUDZone[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUDZone[playerid], 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.
