/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:ui_website;
new Text:ui_clock;

//TEXTDRAWS
ui_website = TextDrawCreate(70.000000, 428.000000, "www.gta-tg.com");
TextDrawFont(ui_website, 2);
TextDrawLetterSize(ui_website, 0.174998, 1.100000);
TextDrawTextSize(ui_website, 400.000000, 18.500000);
TextDrawSetOutline(ui_website, 1);
TextDrawSetShadow(ui_website, 0);
TextDrawAlignment(ui_website, 2);
TextDrawColor(ui_website, -1);
TextDrawBackgroundColor(ui_website, 255);
TextDrawBoxColor(ui_website, 50);
TextDrawUseBox(ui_website, 0);
TextDrawSetProportional(ui_website, 1);
TextDrawSetSelectable(ui_website, 0);

ui_clock = TextDrawCreate(618.000000, 6.000000, "~y~6 May ~w~18:50:07");
TextDrawFont(ui_clock, 3);
TextDrawLetterSize(ui_clock, 0.487497, 1.349997);
TextDrawTextSize(ui_clock, 400.000000, 18.500000);
TextDrawSetOutline(ui_clock, 2);
TextDrawSetShadow(ui_clock, 0);
TextDrawAlignment(ui_clock, 3);
TextDrawColor(ui_clock, -1);
TextDrawBackgroundColor(ui_clock, 255);
TextDrawBoxColor(ui_clock, 50);
TextDrawUseBox(ui_clock, 0);
TextDrawSetProportional(ui_clock, 1);
TextDrawSetSelectable(ui_clock, 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, ui_website); //Shows Textdraw for Player.
TextDrawShowForAll(ui_website); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, ui_website); //Hides TextDraw for player.
TextDrawHideForAll(ui_website); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, ui_website[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, ui_website[playerid]); //Hides PlayerTextDraw for player.
